### ISSUE TITLE
Running hexo generate

### ISSUE THREAD

**Issue by djmtype** [naeramarth7/hexo-command-gzip#2]
With this plugin installed, running `hexo generate` does not compress (remove white space) from the files inside the public directory.

Running `hexo gzip` compressed everything in the public directory as binary.

**Comment by naeramarth7** [comment]
Hey @djmtype. I guess the term "compressing" is somewhat ambiguous.

What `hexo-command-gzip` does is not _minifying_ the files, as for example [hexo-all-minifier](https://github.com/chenzhutian/hexo-all-minifier) does. It rather uses gzip to significantly reduce file sizes (see [HTTP compression](https://en.wikipedia.org/wiki/HTTP_compression)). That's why the resulting files look like binaries (i.e. gzip compressed files).

This plugin is intended to gzip files which will be deployed to a *static file server* (such as AWS S3) which does not support gzip on-the-fly. Since the plugin also set's the file headers, the files will be unzipped by the browser.
